### ISSUE TITLE
GUI Bug

### ISSUE THREAD

**Issue by hanhau** [LordSmooches/Beta#1]
This error accurs on my screen (1440p) while in windowed mode.
Still remained, even with the update.

[![https://gyazo.com/8d3a756f379c55557f55f0d2f5d64bc4](https://i.gyazo.com/8d3a756f379c55557f55f0d2f5d64bc4.png)](https://gyazo.com/8d3a756f379c55557f55f0d2f5d64bc4)

[![https://gyazo.com/8e18a03ee8a4b44839a9de86df46ad72](https://i.gyazo.com/8e18a03ee8a4b44839a9de86df46ad72.png)](https://gyazo.com/8e18a03ee8a4b44839a9de86df46ad72)

[![https://gyazo.com/6da1c60365d76af37823844ddff2c9dd](https://i.gyazo.com/6da1c60365d76af37823844ddff2c9dd.png)](https://gyazo.com/6da1c60365d76af37823844ddff2c9dd)

**Comment by DuncanGarrettBWG** [comment]
Same problem, full screen after the update.
