### ISSUE TITLE
Vase Issue #2

### ISSUE THREAD

**Issue by hanhau** [LordSmooches/Beta#18]
What I did was smashing the vase while picking it up. I got stuck in this animation and a skeleton did the rest. Also cant skip this "Game Over" Screen.

[![https://gyazo.com/a8651741a90030b29600298520fb3774](https://i.gyazo.com/a8651741a90030b29600298520fb3774.gif)](https://gyazo.com/a8651741a90030b29600298520fb3774)

**Comment by LordSmooches** [comment]
This is dealing with the death sequence issue
