### ISSUE TITLE
Enemy spawn / weird behaviour

### ISSUE THREAD

**Issue by hanhau** [LordSmooches/Beta#3]
The triggering area seems to be a bit off, this "bug" can be seen sometimes more or less in the map. 

[![https://gyazo.com/949d41ae4562ab11c80ed572af22d386](https://i.gyazo.com/949d41ae4562ab11c80ed572af22d386.gif)](https://gyazo.com/949d41ae4562ab11c80ed572af22d386)

**Comment by DuncanGarrettBWG** [comment]
Also getting this. If you go to the room southeast of the intro room this happens, and the metaknight bat things spawn outside of the room completely.

**Comment by DuncanGarrettBWG** [comment]
This issue persists in 0.1B.

**Comment by LordSmooches** [comment]
Looks to fixed, Please be sure the latest build is at the bottom of the release screen. https://github.com/LordSmooches/Beta/releases/download/V0.1B
